apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paste
spec:
  rules:
  - host: kpaste.preprod.dev.infomaniak.ch
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: paste
              port:
                name: http
