apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paste
resources:
  - ../../bases
transformers:
  - labels.yaml
patchesStrategicMerge:
  - ingress.yaml
replicas:
  - name: paste
    count: 2
images:
  - name: registry.infomaniak.com:443/infomaniak/paste
    newTag: 1.6.0-rc.1 # {"$imagepolicy": "flux-system:kpaste-preprod:tag"}
  - name: nginx/nginx-prometheus-exporter
    newTag: 0.11.0
