apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paste
resources:
  - ../../bases
transformers:
  - labels.yaml
patchesStrategicMerge:
  - ingress.yaml
images:
  - name: registry.infomaniak.com:443/infomaniak/paste
    newTag: 1.3.0-rc.5 # {"$imagepolicy": "kpaste:paste-preprod:tag"}
  - name: nginx/nginx-prometheus-exporter
    newTag: 0.11.0
