apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kpaste
resources:
  - ../../bases
replicas:
  - name: paste
    count: 2
images:
  - name: registry.infomaniak.com:443/infomaniak/paste
    newTag: 2.0.9 # {"$imagepolicy": "flux-system:kpaste-prod:tag"}
  - name: docker.io/nginx/nginx-prometheus-exporter
    newTag: 0.11.0
