apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:/o0qRDmTNo4IPl/83cJWy3rzRA7h4UgjaqLRonM5bEDgwl1cKWGCFYia7/vyiv8J0WWH+aVFZzy3XdPuYtO0sYVTiKtQ6Ln7Mc1XyhCLeBprMn59cqmxIoNxkQtxyB+GDDQyP5wyiygjj3WpOUOmou9qrXWzUvpZ0TXRBSkj8BCBsI42V8L/DNA0E5i86z/VKMc85biOIPYmGDV7msr7yRH301zwkmNyR0PjZbSDyLuF+6gjFYovd6RIuABL0nce/hv8UoGcd7lmJuQfUogBWDSBJpq2U8q49T9ImhMMfmTtd1KSV6I3FMQQYkQsQNP+clUII1zDfgH6zBSBnONAkjpizRuFQNtS2r9c5mQB6y3w92j7tPt+T+UezoYZEPnIhiOvX4txP+n2H41W2DlrjXCCE7YN3As7Bg8AFqQWjnZrGcIjM8sVVSk9mISQ4vjVNIbiimjqkR9EsI12gIBD/eLgJNaPhwECm9SFc66cYbd3wTabHRmNRHjpV1CIRrvujzUmYNcb4kYEv9EUW1yTiJ4/RYHj5cdV8Rei1ZXI3NxvRgpNLmegCeT30BAnNNVkntRONryprJMs+gw1P5zqqA6V8iBoIL3seGP0SLcQLcGGFUVCDcRnPgbHDTUXI9RtF7yD22/ITfKyu5WgEUoVMXwoivv9Fi361kCrQbELQLhWRpr3oFDgCh9jQ9r8Hfcxy6KqL8X7Y7u9Yojx/BnxRVKDgQ10+ePHhUig8go8ReBZylLTMoXbUDWe9i4+KmFBDcIryL+JvToawP4zKlg5IjtrgW3ymcii3MKZmY/vVaLIVGER3croXOGmGm+2FvqwX4SkTpWdbomPGSc3gzW7bEwo1/zGzdrnZu9oLkS4lByquivgB1wGDm25Cep/8r9m3Mb2KZjFEtoxaA04mZ8vXMRxeVdkdCX9afPGdDShoh1iNWT2fRCaBEtLKmnDQsD3JfCNqILhYSFvmWJDbuRcbh19RwEoT1Atfv4QW5k9YncnA5lllPlFRVa5wtWyburcuBTuilYzv0GOChV9TlkCi/VQC1c+UQNzfoBa1YWg6mw=,iv:LB4gc6k+74joiTWYWwoegBNvqnD2lVjjmBKxzioQGOc=,tag:tXdkfFt3qMmPk+U/eWUXNg==,type:str]
kind: Secret
metadata:
    name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-08T06:44:48Z"
    mac: ENC[AES256_GCM,data:BvHCvaiQUotwBgXS1aNMhsZ1MJcuxYx0ACAO4uKiW8SlE4t42tF83NnX+Kvg1K0PqVaoASx7tYf3HXor6H0v5DBlx359+hRja7J3a+f+MQPU4QL3jm7IJNL/jEvQIsXEA7qtMD1ABncjUnl5pC9KBPyNf+dvJb/Sh+B9NWUks+Q=,iv:QlvrbzOFdeJT9rf4M0pysmlvn+pqMt5XK7OJkMdCwto=,tag:A/NRg1YT1RTueKpqgEadHw==,type:str]
    pgp:
        - created_at: "2024-08-08T06:44:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4pH315BwPYDAQ/+PgWgjMcAT6wbu6+aGCS1Bh1a3H35vLt7AzWkHgo0bvSF
            /oyiEz5+RO4uZyOda12VQVtBy4vgB0ns4XhnoGAekkFfbeaySxHnH6G4Cd1deDNd
            N6zjkggmgMr046EKjKVruBxcCNOtFi72wKwjzuecLh0o0+D+yNK2PgjUTMRBwqij
            1p91Bp4z/7i7xuJuEsgTGXk9Qvq6JgxC8d0s5wtkigFC7OXZcMmls9c1gsbxK8lu
            R8u18PUUQUaU2WMdv/aEICXlr4pqYwS5BgjHpPtge30IsGbAVGUQv66qeLbOGWyW
            YtvVX1DS2/gvOsWVr/oejgH0KJaYUWFuH9dmaxAemUDVpbzcd6SmuTrEhXxSlfZ9
            ojuAlruh5lc0D9eoqpxfTgKyV5FE59PyY+sZ6ZQHzeGg7STrDWVj9RZ5E3Ro6Vg9
            Xs+isXCUZdGqOICpWsHfn6bQF5Q/hRj0M9gXIQq5VKb8GFPkWmm92ZflHKZMkqQd
            3nvfdauuNT8w9vJXxFchFhk88ujd4iEkNhfnikZy7TYaAzx8jvRoXnsL5Uat/5gL
            fXSbVXVoPZzMxQIDJnjB2jap4A+fW/zdBDgsYYO+wMFxqjwozLVE9mD4jIROkgzc
            yPXFWZlETBTSlh3Pg0zNG17WbCODx/U64DFN9N02USeqSQXBtQJsHECx8v3L8tDS
            XgHLrNGefwTwbrWV+mfciIZckowCraOItaXhyLPwqM8Bb7rYDwWUtzXBRETD7Fb3
            qXdSRaNnPTsbu+IEMKKzL1f6i5iuNRxCRKgMNNL6zpU9bzybwmVNwoRVmqa6X54=
            =W/cX
            -----END PGP MESSAGE-----
          fp: 7120085E6161EB9ABC2FD0117C26F0446A4D9603
        - created_at: "2024-08-08T06:44:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA5b0REtfwpx2AQf/er2gBuJj4pBtaUA+aAhv2iuQRCHuutCvxvUC5eN+RJT7
            1uFYZl/k7tnjE1r0u50cvHKSX1ZN1wBbgnXHyvN6eqDsowAQnTmj4Lqm5V0DUt7V
            Ru7/9l6/pibDBk4ue511JIkclJhdveAVBoh5gSGR0QqMgS2UkSCr1inVOtQoxTbH
            a9ca6xyMQE7N5ODHN5iuhzgEtypWU+VWOA+oK8qHJ4Ej21yRcRXIMS3e+o1oLE7I
            qA9ivjag6y/QpC7byPT5nYSCkAUmz5kvsU7vADfyCp/HzkL9XugbUrhVyzMGLvMe
            kqjcNTkPi9ryL0IZztUSvQYVkNxnwrleXYD583m7K9JeAVm62pZI0VqOGd7YCrpD
            8dVwsTOA6Ze0VP0yEb5M7a7eYosaQnLX6I6ydBfW1GYAKv8owJbc/x30ilwDn62p
            PYSrlGMWDc/n0xGziVSBFrcDVf7DskUXjnf85K5bOg==
            =zvII
            -----END PGP MESSAGE-----
          fp: 6AAB0E0F2B1D6B6DDF722EBD0E49033003EE36D7
        - created_at: "2024-08-08T06:44:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3kl+hZF6SyvAQ//bXkAv4gN+2CBsBrl5TsOZUkrqJhFCGMrzJeVZtsXHcEW
            8ytfZZGDI7gk1ph/KQY2auXzSlsvijEbeter08+/q3/xcu5x6EOXTxpzYJ21ZxtK
            Wkbj2KVdLi7TluWULn++yw/p7DIwr2yKB07n8seYyPl7vEoi3p1SnbxZi/LJ2pmT
            d+sErOSRHnixMNljOck7axjRk1ShicJXvZqp1KUjOQqz2iStcQSe9xiJvtq1Jo4f
            8xbfAqNdXNEMzJwmNU9jdCWUH5IPLQNLn8sCYQ/TO025+QhxGVXRgVQzjz3RL27s
            7Z0DUb30HkgAEN+p4o961QVu2+72NBM9SyW+CzAVok/aST/rSi+1zvtJXpb2kTB3
            +eUa4zyGMki8VZbTYi3GrgW0jXYP9nv3pHe8kvx6vJppXdvR/ofW2bMdgFVhjy1w
            070THtAl0fqrzjzI1QfFPTpRT3Pj0YCQVPrsfjgCqiC96sD2dFAwx966OPe8Ipbk
            wUoYaJLsJUxWEhTJjcEfDJf+4fUDptp2UpxmQw386T49ZGkwK+jrrcPKpG4LpB+M
            0X3JsjR8QIiLajPshvRDr6Aln8vDAB/ZeoyaQU1veX1Vo4FJEte/SH9G5xLfVG1Y
            ILmZelmfUIcDfI85f3f2L6dMKi/7YM+2D5xWzCJix+b1hCjuXa8PjHXuKhbN2eHS
            XgFO6I5xWUl47Ax3+6562wUjhcyhYte9iHVfZWsZcWtr+TJFWi49tmdV25T/h6l9
            AzBEgDoSPOPXLiCe8ResxpKt4qYMzWRx1e7M5EOMjFSP3HZ3bcGwwIdw/P03nRw=
            =HoMn
            -----END PGP MESSAGE-----
          fp: 746B90C141BC872A4C1D24275BC311B9B60A919B
        - created_at: "2024-08-08T06:44:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2nntK83Q466AQ/+JnwlJWFlS8MgDY8Ckq/6+pDXa4Pq2WBBF55GmMZUJwbG
            3PllI0ZV+uZs/uZ/fM89O1BrrD3v/j1h6hOIP2284Jem9BlmsEB2gdGEV0DGHtyI
            hVsHPskbpOcGP946g/IgctjYtwjUNQK6SuMrHg9GI9UT4uqaioT/Z2PWIJSYQbGd
            XmD5XSmDrRYdwJXARE2Rs5J70Gw2hxJBg/L5uKhuaYJEfKG5JgxfQ2UQqUE1R32c
            LKHRrWIwV8jyq3ulIRb9Jcdsc9UnlFeR6DGlqE8YDKCbORV302hJNR+LX5kZv43K
            py2C6CRzde7au1l01BIPOH8yp+yn5IN41drhMU5f860zw7ycvEkcW4edfINfuETt
            kkduEXudVm687Wm2GZ+S8ZZVvh2Vo92sFQeu73CWoTN7qfsanvw6YiksE3XFZUgH
            tbLiQtUhl4qvcTyb6WYXWDx56k6uFeFFd/GBHS99ihfJjJ32YmzGA07sbVkeeoPQ
            330qbIdiygM1lCvF4RK0H/U/+QZp11OpwsMzwpIy2jBPN3jqR5S0EFpWTUwj+Bnz
            yPp+RGz0pI23Ba29tFQ7qXU3U47DuchXjOVOOZ4oH/RwzdliQtNcWv9Yvlp/EhZ8
            CeP+HeAzmHi6cOkUA7lb3+hPs4B4Y3zM1Snt66W8/qQnUWCHZTeEm7W+ECvlE5zS
            XgFf9AOJh6wkCAuBNEiytPMWCrAGlZKCzhumZ1HWLl/l2RiFOT753D2Egygi8Z4a
            jXUg0hlnNjYAFf6xywLhyxhy0blDwd27iTCm0HJf5yEj1b9MQGF7KMvc1wtzOvk=
            =q1XN
            -----END PGP MESSAGE-----
          fp: E63340DAF5C91B4B18D1000469E7B4AF37438EBA
        - created_at: "2024-08-08T06:44:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxwJOACjHgHaAQ/8CVll3CsYqk/8OUgTMCZGfd9GOhCiCmzy6DCZGIyH1yPL
            xaGwt+tNDM7mtSMj2pyfZfIZRTvzSInVj62sDeXp8OIqlynaVHCk7op5pGTr3ruD
            Jq4uRgGY9g6c+M+wZPMn100ubjdrwiPJ2YsOLydnjJv1c0GQOqLlatbcRS6VSK5K
            MRMT6EchYC/S5+Xcv7xfoyeHFPEWBDWahk0ve3NdibOZ15MngEXzKTBPR9WLi4ks
            Kdf8EVMAWURVhgCV4uRcMlw/mJKK32NlTUnT8eybzy7mgIUh3d4w1jsYAIO77QDW
            XUDF8ul5XDzpbXafqAe2k84yOznECQj9q8zsVg69zYk+Kf8QVlNTISefojDyR6KC
            ldezzPSpEvbrsjQr1iPPNNS5QAH+O57ncVWxFJRcCtRQ6LcXMZZFMWd8nh6QvciH
            vlgUZ9C8UyJN7Bj2DbicVFuOMmYEeUBVsdV0Cn/J7L+NHL4uHHxJilOTzq3xZmhA
            TjiQG9OrzjL09XQmEKJnMp4mMT5cxqYKwGkcQmTEvPQsXyK4SDxxTzd8RmBBmiiq
            0eeBUzJhIDttJmesz1jE+vuVsA0utxH75D+e/hqdSoUJWJsId37NFskWum1Tuh22
            afx+Nva8uU3+ojQd9WPgDEX/dQ4UtMGSU3i+8A8EkRKV0PqBHSjT1p0HCElaA4zS
            XgEl8yk+cQhYzbShn9UCBEhoS4tXQezqtyBY5NRxsF1S+tKUsW5jN5/e8EvVza3K
            cFzIZMIXg5/5beqs6gCx9sYIBNP0BfWfVaCatjFzKaf7OTGWbd7e7oBTdD0wvUQ=
            =H+zU
            -----END PGP MESSAGE-----
          fp: 9113D4BD7F165A67FA4CFEE4BA45544DD163028F
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
