apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:kt1SlWtMrlLYgQiP9h+8Js46WznYoJDN9/FX61Udh4YKMThgLiLaypvCmVeqJGwP3rZIbHYVmNnjudUCVjeInh6KKwk86GXa5NWh7EBT2sqUoRphn2y7v+nQP3lJ2mODt78IITrUqg1KfE/XE6yIO2x8N/ds0JTPoK9X0TjKvns2O4xsaYpnEICpy70QezqdYxfEcw4ldFnj6jcjLHG8P5JKKrpqEpIgThsiwS+Xobt//CpwPhB6V3OjSU+D0rO3LKHbB1GiVoa4u+fRj7DIMF1j0bGzio8m+3P0ycWRFm5bVzY/1KTk7JH/PhFLiMUUHnUr0DE2De913Cene8Q4k9yHMlT82jnUagyoQqPyJqKztvxOkZ1jSmlVmQsXxGYXc8415Q1JEhqlXUTPOcBO63s6WRJFCvaGwImNQCNrubfOmVmHz52dqqZt4bw7KxH7G0bOwGcBsNIeXJzu4R3VEgXAQviklvcOQh38+G7TU8oUxOjk6q1XGjqasORD17BI4BqttWNkpAWfnoEX7icblttiy1byocnElr8wUjv7MIdmdfP7yoLm3H738Xs4CJofQo39pJ+KBXehbF+Co5dBwiLH7h59gZ22iKNI0trFzDC0wzv5do7dDhPcYUQgIoLoyHVxBtTnbGYY14nlQIJ1JJ7TSLDReIcEv+l3pnXlrl/s8QdbDKD5jHwkkpsEsuHiCuwnLVYEpQToJVTx82uUWACW5UoD44U8+wh5TsrjplCFckTGFMxSPcEKYUdKcKoExeyz184gvYtDEo3YrPPlggZhLpzwLe98rB57dEsznSPp/l0GlqEGYQjlwdo9bSgGiJVqJuXwzNC8K7OOkM8bDLJdrJEOhQA/QWcl0DyU94IAaIyd99xRW5NsS51iTMpTJHtAJae+s75t+2fIaCsUh/USWmMTvfwQGd3mkvZlALdB57XFgn5y/EXE2u7HzY5yDYyWVIckt8pgzMhENukrqjGXwVUpNaJn1z2mav8gYKOEKgm/88WBMrVOXwoEoMwxCqGKxjVi6G76gXhyl7TLVauWNQ4H/wIolLh4CVBQvfA=,iv:2YAqSTh2Sc4zieF5H06vLVHP9NcfDIvT6JoD91WDbEg=,tag:GkkaG6cwLS7rfFdeWC9hUQ==,type:str]
kind: Secret
metadata:
    name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
sops:
    lastmodified: "2026-03-18T13:10:26Z"
    mac: ENC[AES256_GCM,data:AztelzBcuxKu1LeV4FuxLK5oN/D8DuL3+u9ri/lCqr/CGw4DhbU2TnZX/8R2+6c4tn16Q/o0fZdOqCuX7uIGT0qaeenKYfG7P863Nu55Fig91P/YV8KeiR+r78UOf8Ar/fE+T3QsjXGBTsNDXJtE91ge5KxGECGL4L9+EF7Qo2U=,iv:Ql1pEJ26e1D4F5tizmd6R3L4rCmqg8iAUAonALpzoEg=,tag:mfuvstFcrnI0CfLj62FOXg==,type:str]
    pgp:
        - created_at: "2026-03-18T13:10:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4pH315BwPYDAQ/+NSqaJurL+UzL9fZ232qpLLM92TQ4WFi4Nuxz7C/DadaC
            CjFXyNhANm1lZ0LAU4goZ2/JXEGr8OuDvBxUqOgME33rHZ0XBuypnUkmSQKZWBWT
            po68Jbmbz8Q7WKe669VHvgiEOeKZMDrAWCtq9LFwZMz8j96kHaKULwGW4eUIWe2w
            Wn8ZnATo3apUX+G4w+YJnbp5p6DE1otu1tIxOdG7zO4PKpI0MepfwS/Pa4f/elQD
            jmTgsYzHiNP2RVBHTNiL7Tvoz0TUihA0y//3NDWouMlDEuPXHnoA+oSF1xzVbVDl
            EpUbS3WqxiwauJsqz/rMasceMn+onE3LEWH+HMoS/o1nE94SRH9IqIx0wYIuHsBb
            cB4ZyvzDSNeR4hptBY4czaim3mhzKulQ5wRjr4GxqA85t7r4p4GybZXSizqgEgfX
            1oKgFBrXxbi7rWTB+hpx0jidsjtiePQUilYaLU1pb4GjscLQRo3LcSpQK8fakB4l
            kWZShQWUJiKaFUhwDDvPRsAeFz1LaeXgNZN3ZmdAaeFDOCpu5RgyPHPBwKZ5p07B
            pFbOPFWM2fUIyb00cZJ0PyG0JnNZ5nUvsHl/AW5DIhmEkLULTVNflclhf/ASmn7D
            rQ1Gw6B/fdiTyXwL8GZbQ8JjdLoeeYYfrPO/VePpn+ncTtZSh29mmHISRvYkihXS
            XgFtQAHaYr/Kx1uJ8nskLi10r4gk0qhrFrPCaFijPlxEA6ECqi9hrnsxsMazwdQt
            rmtnF1aWIBKO+SgyOBqGTX73l+nOxSk3qi+zqGsSa59y0lBVnWlag6Q9QMeZr1Y=
            =AjAY
            -----END PGP MESSAGE-----
          fp: 7120085E6161EB9ABC2FD0117C26F0446A4D9603
        - created_at: "2026-03-18T13:10:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA5b0REtfwpx2AQf+JRFM0OW0zd0Ch8WWiF07Rd3TIWr148iRmkfN2D+0u5PL
            OR/VFUzgjEW+Q+6LjEHkteaJGBX+rJJs3tFWkgpWMZzzL3HUpNBh6G8qhqbqj39F
            8Hdu7IXVRegKxEK1e5e/25s6o8bKgwX6QQpisttegiP42Th5yDu1COebpwjLzXeD
            VswX/5BNT4YQU0JRxy+NamiKxj1DcvhDp/ZHY6vqouSnKOoGMCqPAp0xwDXDWzYA
            duIyJZkE8k5beY4A9zXgYiDUxVrQeB7rzznsSIh2MmTDXNXE1KsjOmwPYvo9p6Yg
            +lfpKSGx6VJc3q3AQ3LqE82qU7KM1XEy9JqQqq+0lNJeAQvgAxjp8DC2Jxs9eqdv
            Wez6xPrGSRF+B7rz5Rt8k20CmRbcHJDg5hnvpTq+wtDe05MhEn8OFDB9z2+BMLWq
            nOtcJBF6wwX5dRfVwyfu28lqDtiXOezvcxdZSaHOZQ==
            =DJ5O
            -----END PGP MESSAGE-----
          fp: 6AAB0E0F2B1D6B6DDF722EBD0E49033003EE36D7
        - created_at: "2026-03-18T13:10:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3kl+hZF6SyvARAAruofqnyQCMyrA7P1lg70kr5LK5Nh3+YXtd2/shfPZIYV
            msKOhELmIcUbvYdepEYNZIWWePvKhBA6eGeIEgOiU9sg4Lie/9RY8Qg2JpRi3j0q
            yGIjspQcCIEw1mu1epi5lweNVuaII2s4EnaBiugDGmXnaRyrwdXYNrFZr8RT6H6L
            Hdm1ys58fhADKoIjjES4StqvrEQ1e+EkxelNAZFoKqQ7Gc6u9eHACakRQ45mqvPW
            3AOYfwQ9osn1fuOKFtNHEQsARveO6Uwu2xg8IGI7IZVzBTmX7jNBhF3GqW1SnzOd
            bFeUfpR/kV2RHjaQnyTIYjHwwJS5FjOYK+n+tlElqbsiTGKOpMshsjyUCAxddevy
            4HSc0zJt6wzTFWnBozxDWXaVEa7jLqlDwEsx7L6Rp3KDZ+mqQicCP4F3LIODcGWl
            TpiR38VwsovHabnTKiFIeV1dAkHPYLsuI/V4xBSAg7HqIYXJmi6e+epIrt7a8GXc
            swQP/46kMFNy7ouMSrN/ZhnU53+bPCRDk/8TP0fHIDDcJ2V56vRcChILzjICceZ1
            TNLZd+3QpggzeH/9JmYRyxfsd20GSyBbOH0OgqRKUqeWULvkRNkjNhAShx1v0i27
            yOZYcQPMi61MzrqY2zHRcp1Xkl6xaiMGibIf6M473wCUW4lDARHJxxvzWH/4/i7S
            XgEYjzGEmccUKmN91QattKjUg4OVVTQ0RA+U34oBPslSEapZWIeYLJQp+KTX6tzR
            1ArL9MQexxNHuT9TOVtHFkXfn4BYJ/DYtODIBsx6Ea+F2NZnDYjEPFkd6IAhMLs=
            =Yr+i
            -----END PGP MESSAGE-----
          fp: 746B90C141BC872A4C1D24275BC311B9B60A919B
        - created_at: "2026-03-18T13:10:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyhrFRUTbcM/AQ/9HI4Sv0J5YcUBS+B/oCy5ofmLmW2GEMDyD7PSBPSYTVUz
            eF6ykfgtC9tutbo7W8ISMhAY3jYhP4FmmeWoNfi12ixvRht3p49vZ2eB4M3FRtrD
            FLfjr6EqlyuLaPtyuGyB3wvwzpODk7c8QQkA0lAmJ6bjTDMJndXNSg3eepQOsCsh
            4LX6gtWXm/aSqjW0+9HsTxLZN3SjbLMHf/0ivze2DXQAUV2DzN9ffjU+VQA6FTfO
            FM1e4+BqBsnCTagtiLmGoJlnlRqRSFOeFORj4D4sJ4Lws+kPZXVo3ZChzcedg1Sd
            RMtDInNOHXJ0/fXdf3yIn60n7qdeaVF+w36RkpOCkuywd1NtUMN6tiE6NCFnjIn4
            vKNgEguBOZeupiXF6756po83CaONR0qLPmd56hcnaLk7KUCNAQ4g77n4qRgngkEp
            wb2jqB6yySFIcpwhZv8WS0IrmjNjfntS9RB7rp0FqMr5eksNY7vFk/2lQqgTpJUX
            0w+F+f9cDOJMJ1wUvkNxKeENBGh9wsS5OkfOnmeDws8/BLWtrsGlLBrh03s3M/sc
            RNr6PtA09Jt/qXVduSsaQRnKl56OhiqGBe7RgZd5YBznQufD1EQJkye4ej5jiNRh
            3PVJ29wlhjVCqaoCKHoYmgflfmFN8i9d1a4EDAg3Dq9rJNU7PYUFxw8fOWz1ssfS
            XgHH+5MXx5zBYc+P+y0M4Wo5HxHP6n2lVoYcN/ut9P5fhsY8pthTZxScB+lQIsmP
            PcWH4CPAhNCFL2uvSAh0mbGljF4ueUvm2wUk0PYzilg0ETZAjeFPrqDAGlukiXI=
            =VjYh
            -----END PGP MESSAGE-----
          fp: 514BFEC9402BB1E2BD0F3629286B1515136DC33F
        - created_at: "2026-03-18T13:10:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0usXZ7HqfmDAQ/8CPl51hxxVYAtnHKO+sx6kGsAnAGs3yF/Pt7WgmXN2X2h
            eYB10m5fnGpwmZmwSOS39V2XpkM/XKsFjbLpzyl+7wONmu8H6asX1u0up/eNPODa
            tecIr0tBTdvpJLBx2/g3AohPixL125jekOaal8jxbUMXlRV6Eck9c08oQ3f4wqsn
            HkleM8ajEA5krsXuAiHETVaXAoSQEPjFLy5vvPvZTRnNhK1/PNoTRmasNssqcX3P
            gimJAufGVecAcQPjFGfjGCzaOU7XCwK5mVmDFz93Pf6PPVfD2BY2/wgBHSxvsRSI
            ozYaP15c3ysBmsdDU4TEXVP/XDVxPnl+AgjlAMR5nd4KbVnqFp+pOOyNf1Ja1zDi
            bCdiF7PufUJhnlekgNuDg4H4xXvOqenjPXinLai5kIjIKRahhBDAcnKcFmE/L9yR
            27KwznazUStvkPX1FBkbMNnkSKfLMVet4QfUdoCC7xX8wUnC48IC+J2vRkuvU/hX
            9OKUr2xBHoK2CNkTl0OuCo+OBZEDh4hRXvgQscISGA5TlSvLfsc3eMbSCwgp4qHL
            3TWRY393VbHGOAbBjkQboyrwUQ+nLU81d/ikyZHI3acetKNR1iduRePat3ysVMNJ
            UCjjOQRnwkuHzSHs+EcwhxMeyk8fYnQSjFqrl6nc/lrZ8FjTPJDOC1FDmUjDSQ3S
            XgEnnTxd9VdHkWack8m5z2NJvouOXRZ2K/+pGQayLfPY11nWZNSyJDViEGTkwTNv
            EU86GYUJtkd2UYpVKnOXglHllRdhnUWPNz7FHMbeuYhX8l7DMWSO4aizk12Wfow=
            =XHuk
            -----END PGP MESSAGE-----
          fp: 02A6376F3A7A69953C9ECAD31D7382865D865488
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
