kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: paste
  annotations:
    kubernetes.io/ingress.class: nginx-paste
spec:
  tls:
  - hosts:
    - kpaste.infomaniak.com
  rules:
  - host: kpaste.infomaniak.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: paste
          servicePort: http
